name: FUSS_Env

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: FUSS_Apache_Web
    volumes:
      - ../src:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db 
    environment:
      MYSQL_HOST: db 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: FUSS_DB

    restart: "no"

  db:
    image: mysql:8.0 
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: FUSS_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d
    restart: "no"

volumes:
  db_data:
